name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Bump version
        run: |
          git config user.email "junichi.sugiura@dappface.com"
          git config user.name "LukeSugiura"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          version=$(basename ${GITHUB_REF})
          npm version ${version} --no-git-tag-version
          git add -A
          git commit -m "Bump package version to ${version}"
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Prepare npm token
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish to npm
        run: npm publish .
      - name: Push version change to GitHub
        run: git push origin master
