name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Switch node version
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.3"
      - name: Install dependencies
        run: npm i
      - name: Check lint error
        run: npm run lint
